### Get all tasks
GET http://localhost:8080/api/tasks

### Get task by ID
GET http://localhost:8080/api/tasks/1

### Create task
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
    "title": "New task",
    "description": "Created via REST Client"
}

### Update task
PUT http://localhost:8080/api/tasks/1
Content-Type: application/json

{
    "title": "Updated title",
    "description": "Updated description",
    "completed": true
}

### Toggle task completion
PATCH http://localhost:8080/api/tasks/1/toggle

### Delete task
DELETE http://localhost:8080/api/tasks/1

### Search tasks by keyword
GET http://localhost:8080/api/tasks/search?keyword=bug

### Get incomplete tasks only
GET http://localhost:8080/api/tasks/incomplete
